---
# Entrypoint for Zuul
- project:
    check:
      jobs:
        - pre-commit
        - packit-service-tests
        - packit-service-tests-requre
    gate:
      jobs:
        - pre-commit

- job:
    name: packit-service-tests
    parent: base
    description: Run tests of packit-service
    run: files/zuul-tests.yaml

- job:
    name: packit-service-tests-requre
    parent: base
    description: Run tests with requre support in a cluster
    # this will clone the deployment repo to a predictable path
    required-projects:
      - github.com/packit/deployment
    pre-run:
      #- files/setup-openshift.yaml
      #- files/packit-service-image.yaml
      - files/deployment.yaml
    extra-vars:
      with_testing: true
    run: files/zuul-tests-requre.yaml
