# Install dependencies from setup.cfg as rpm packages for ogr
- name: Download script setupcfg2rpm.py
  get_url:
    url: https://raw.githubusercontent.com/packit-service/deployment/main/scripts/setupcfg2rpm.py
    dest: ./setupcfg2rpm.py
    mode: "0744"
    validate_certs: no
- name: Download ogr setup.cfg
  get_url:
    # ogr has only main branch
    url: https://raw.githubusercontent.com/packit-service/ogr/main/setup.cfg
    dest: ./ogr_setup.cfg
- name: Install ogr dependencies provided by setupcfg2rpm
  shell: dnf install $(./setupcfg2rpm.py ogr_setup.cfg) -y
  args:
    warn: no
  become: true
