---
# This file is the entrypoint to deploy packit-service to an openshift cluster (e.g. in Zuul)
- name: Deploy dev version of packit-service into zuul.
  hosts: all
  vars:
    deployment_dir: "{{ ansible_user_dir }}/{{ zuul.projects['github.com/packit/deployment'].src_dir }}"
    project_dir: "{{ ansible_user_dir }}/{{ zuul.project.src_dir }}"
    as_root: true # needs to run as root in zuul
  tasks:
    - name: Generate keys in deployment_dir
      command: "openssl genrsa -out {{ deployment_dir }}/{{ item }} 4096"
      with_items:
        - private-key.pem

    - name: Generate keys in project_dir
      command: "openssl genrsa -out {{ project_dir }}/{{ item }} 4096"
      with_items:
        - private-key.pem
