---
- name: Install dependencies for packit-service.
  hosts: all
  tasks:
  - name: pip install pyasn1-modules
    pip:
      # (see #131), remove once image is based on F30 (#110) or we remove packitos/sandcastle dependency (#109)
      name: pyasn1-modules
      executable: pip3
  - name: Install all RPM/python packages needed to run packit-service.
    dnf:
      name:
      - mod_md
      - python3-flask
      - python3-ipdb  # for easy debugging
      - python3-mod_wsgi
      - python3-fedmsg # packit-service listen-to-fedmsg
      - git # setuptools-scm
      # web service needs packit just for few bits (see #109), so hopefully we don't need it from master and RPM is enough
      - python3-packit
      state: present
