---
- name: This is a recipe for how to cook with packit-service
  hosts: all
  vars:
    home_path: "{{ lookup('env', 'HOME') }}"
    ansible_bender:
      base_image: registry.fedoraproject.org/f29/httpd:2.4
      target_image:
        name: docker.io/usercont/packit-service
        environment:
          FLASK_APP: packit.service.web_hook
        cmd: flask-3 run -h 0.0.0.0
      working_container:
        volumes:
        - '{{ playbook_dir }}:/src:Z'
  tasks:
  - name: Create /usr/share/packit directory
    file:
      state: directory
      path: /usr/share/packit
  - name: Copy packit.wsgi file
    copy:
      src: packit.wsgi
      dest: /usr/share/packit/packit.wsgi
      owner: apache
      group: apache
      mode: 0644
  - name: Comment out the default :8080 port
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^(Listen.+)$'
      line: '# \1'
      backrefs: yes
  - name: stat /src
    stat:
      path: /src
    tags:
    - no-cache
    register: src_path
  - name: Copy fedmsg ssl configuration
    copy:
      src: fedmsg-ssl.py
      dest: /etc/fedmsg.d/ssl.py
  - name: Let's make sure /src is present
    assert:
      that:
      - 'src_path.stat.isdir'
  - name: Install packit-service from /src
    pip:
      name: /src
      executable: pip3
  - name: Clean all the cache files (especially pip)
    file:
      state: absent
      path: ~/.cache/
