---
kind: Template
apiVersion: v1
metadata:
  name: packit-service-tests-template
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: packit-tests
  spec:
    template:
      spec:
        volumes:
        - name: packit-secrets
          secret:
            secretName: packit-secrets
        - name: packit-config
          secret:
            secretName: packit-config
        - name: test-data-pv
          persistentVolumeClaim:
            claimName: test-data-pvc
        restartPolicy: Never
        containers:
        - name: packit-tests
          image: packit-service-tests:latest
          imagePullPolicy: Never  # IfNotPresent
          workingDir: /src-packit-service
          volumeMounts:
          - name: packit-secrets
            mountPath: /secrets
          - name: packit-config
            mountPath: /home/packit/.config
          - mountPath: /tmp/test_data
            name: test-data-pv
          command: ["bash", "/src-packit-service/files/run_tests.sh"]
    backoffLimit: 1
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: test-data-pvc
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 1Gi
